VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = false
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "256"]
    end

    # Web server 1
    config.vm.define "controller" do |controller|
        controller.vm.hostname = "controller"
        controller.vm.provision "shell", path: "install_ansible.sh"
        controller.vm.box = "ubuntu/trusty64"
        controller.vm.network :private_network, ip: "10.0.15.20"
    end

end
